spring:
  application:
    name: chainpay-core

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chainpay_db}
    username: ${SPRING_DATASOURCE_USERNAME:chainpay_user}
    password: ${SPRING_DATASOURCE_PASSWORD:chainpay_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms

chainpay:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  web3:
    rpc-url: ${CHAINPAY_WEB3_RPC_URL:http://localhost:8545}
    chain-id: ${CHAINPAY_WEB3_CHAIN_ID:31337}
    confirmations-required: 12
    hot-wallet-private-key: ${CHAINPAY_HOT_WALLET_KEY:"0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"}
    gateway-contract-address: ${CHAINPAY_GATEWAY_ADDRESS:"0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
